// Generated by CoffeeScript 1.6.3
(function() {
  var calculate_letter_of, is_valid, letters, obtain_number, root, show_error, show_letter;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  letters = ['T', 'R', 'W', 'A', 'G', 'M', 'Y', 'F', 'P', 'D', 'X', 'B', 'N', 'J', 'Z', 'S', 'Q', 'V', 'H', 'L', 'C', 'K', 'E', 'T'];

  root.calculate = function() {
    var letter, number;
    console.log("Vamos a empezar");
    number = obtain_number();
    console.log("number = " + number);
    letter = is_valid(number) ? calculate_letter_of(number) : show_error("It is not a valid number");
    console.log(letter);
    if (letter) {
      return show_letter(letter);
    }
  };

  obtain_number = function() {
    var input;
    input = document.getElementById("input_number");
    return input.value;
  };

  is_valid = function(number) {
    console.log(number.length);
    if (number.length === 8 && !isNaN(number)) {
      return true;
    } else {
      return false;
    }
  };

  show_error = function(message) {
    return alert(message);
  };

  calculate_letter_of = function(number) {
    return letters[number % 23];
  };

  show_letter = function(letter) {
    var text;
    text = document.getElementById("letter");
    return text.innerHTML = letter;
  };

}).call(this);
